server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  application:
    name: event-processor-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/event-db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: event-db-pool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none   # for dev; use validate or none in prod
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: event-processor-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest       # important to consume old messages
      enable-auto-commit: true          # can also use false + manual ack
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


external:
  countries:
    url: https://restcountries.com/v3.1/alpha/{code}
    time-out: 5
    retry: 3
    back-off-delay: 2000

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic:
    incoming: topic-events-raw
    enriched: topic-events-enriched
